import { BoardSpace, SpaceType, ColorGroup } from './types';

export const BOARD_SPACES: BoardSpace[] = [
  { id: 0, name: "GO", type: SpaceType.CORNER, icon: "🏁" },
  { id: 1, name: "Old Kent", type: SpaceType.PROPERTY, price: 60, rent: 2, group: ColorGroup.BROWN },
  { id: 2, name: "Chest", type: SpaceType.CHANCE, icon: "💎" },
  { id: 3, name: "Whitechapel", type: SpaceType.PROPERTY, price: 60, rent: 4, group: ColorGroup.BROWN },
  { id: 4, name: "Tax", type: SpaceType.TAX, price: 200, icon: "💸" },
  { id: 5, name: "Station S", type: SpaceType.RAILROAD, price: 200, rent: 25, icon: "🚂" },
  { id: 6, name: "Angel", type: SpaceType.PROPERTY, price: 100, rent: 6, group: ColorGroup.LIGHTBLUE },
  { id: 7, name: "Chance", type: SpaceType.CHANCE, icon: "❓" },
  { id: 8, name: "Euston", type: SpaceType.PROPERTY, price: 100, rent: 6, group: ColorGroup.LIGHTBLUE },
  { id: 9, name: "Pentonville", type: SpaceType.PROPERTY, price: 120, rent: 8, group: ColorGroup.LIGHTBLUE },
  { id: 10, name: "Jail", type: SpaceType.CORNER, icon: "⛓️" },
  { id: 11, name: "Pall Mall", type: SpaceType.PROPERTY, price: 140, rent: 10, group: ColorGroup.PINK },
  { id: 12, name: "Electric", type: SpaceType.UTILITY, price: 150, rent: 0, icon: "💡" },
  { id: 13, name: "Whitehall", type: SpaceType.PROPERTY, price: 140, rent: 10, group: ColorGroup.PINK },
  { id: 14, name: "Northumber", type: SpaceType.PROPERTY, price: 160, rent: 12, group: ColorGroup.PINK },
  { id: 15, name: "Station W", type: SpaceType.RAILROAD, price: 200, rent: 25, icon: "🚂" },
  { id: 16, name: "Bow St", type: SpaceType.PROPERTY, price: 180, rent: 14, group: ColorGroup.ORANGE },
  { id: 17, name: "Chest", type: SpaceType.CHANCE, icon: "💎" },
  { id: 18, name: "Marlborough", type: SpaceType.PROPERTY, price: 180, rent: 14, group: ColorGroup.ORANGE },
  { id: 19, name: "Vine St", type: SpaceType.PROPERTY, price: 200, rent: 16, group: ColorGroup.ORANGE },
  { id: 20, name: "Free Park", type: SpaceType.CORNER, icon: "🚗" },
  { id: 21, name: "Strand", type: SpaceType.PROPERTY, price: 220, rent: 18, group: ColorGroup.RED },
  { id: 22, name: "Chance", type: SpaceType.CHANCE, icon: "❓" },
  { id: 23, name: "Fleet St", type: SpaceType.PROPERTY, price: 220, rent: 18, group: ColorGroup.RED },
  { id: 24, name: "Trafalgar", type: SpaceType.PROPERTY, price: 240, rent: 20, group: ColorGroup.RED },
  { id: 25, name: "Station N", type: SpaceType.RAILROAD, price: 200, rent: 25, icon: "🚂" },
  { id: 26, name: "Leicester", type: SpaceType.PROPERTY, price: 260, rent: 22, group: ColorGroup.YELLOW },
  { id: 27, name: "Coventry", type: SpaceType.PROPERTY, price: 260, rent: 22, group: ColorGroup.YELLOW },
  { id: 28, name: "Water", type: SpaceType.UTILITY, price: 150, rent: 0, icon: "🚰" },
  { id: 29, name: "Piccadilly", type: SpaceType.PROPERTY, price: 280, rent: 24, group: ColorGroup.YELLOW },
  { id: 30, name: "GoToJail", type: SpaceType.CORNER, icon: "👮" },
  { id: 31, name: "Regent", type: SpaceType.PROPERTY, price: 300, rent: 26, group: ColorGroup.GREEN },
  { id: 32, name: "Oxford", type: SpaceType.PROPERTY, price: 300, rent: 26, group: ColorGroup.GREEN },
  { id: 33, name: "Chest", type: SpaceType.CHANCE, icon: "💎" },
  { id: 34, name: "Bond St", type: SpaceType.PROPERTY, price: 320, rent: 28, group: ColorGroup.GREEN },
  { id: 35, name: "Station E", type: SpaceType.RAILROAD, price: 200, rent: 25, icon: "🚂" },
  { id: 36, name: "Chance", type: SpaceType.CHANCE, icon: "❓" },
  { id: 37, name: "Park Lane", type: SpaceType.PROPERTY, price: 350, rent: 35, group: ColorGroup.BLUE },
  { id: 38, name: "Luxury Tax", type: SpaceType.TAX, price: 100, icon: "💍" },
  { id: 39, name: "Mayfair", type: SpaceType.PROPERTY, price: 400, rent: 50, group: ColorGroup.BLUE },
];

export const TOKENS = ["🎩", "🐕", "🚗", "🚢", "🐈", "🦖", "🐧", "🤖"];
export const PLAYER_COLORS = ["#ef4444", "#3b82f6", "#22c55e", "#eab308", "#a855f7", "#ec4899"];
